name: learn-github-actions
on: [push]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - run: node -v
    - run: echo $GITHUB_REPOSITORY
    - run: echo $GITHUB_REF
    - run: echo $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
